package com.emall.dataobject;

import java.util.List;

public class CategoryDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_category.cat_id
     *
     * @mbg.generated Sun Mar 17 20:04:09 CST 2019
     */
    private Integer catId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_category.cat_parent_id
     *
     * @mbg.generated Sun Mar 17 20:04:09 CST 2019
     */
    private Integer catParentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_category.cat_name
     *
     * @mbg.generated Sun Mar 17 20:04:09 CST 2019
     */
    private String catName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_category.cat_status
     *
     * @mbg.generated Sun Mar 17 20:04:09 CST 2019
     */
    private Boolean catStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_category.sort_order
     *
     * @mbg.generated Sun Mar 17 20:04:09 CST 2019
     */
    private Integer sortOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_category.create_time
     *
     * @mbg.generated Sun Mar 17 20:04:09 CST 2019
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_category.update_time
     *
     * @mbg.generated Sun Mar 17 20:04:09 CST 2019
     */
    private String updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_category.cat_id
     *
     * @return the value of em_category.cat_id
     *
     * @mbg.generated Sun Mar 17 20:04:09 CST 2019
     */
    public Integer getCatId() {
        return catId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_category.cat_id
     *
     * @param catId the value for em_category.cat_id
     *
     * @mbg.generated Sun Mar 17 20:04:09 CST 2019
     */
    public void setCatId(Integer catId) {
        this.catId = catId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_category.cat_parent_id
     *
     * @return the value of em_category.cat_parent_id
     *
     * @mbg.generated Sun Mar 17 20:04:09 CST 2019
     */
    public Integer getCatParentId() {
        return catParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_category.cat_parent_id
     *
     * @param catParentId the value for em_category.cat_parent_id
     *
     * @mbg.generated Sun Mar 17 20:04:09 CST 2019
     */
    public void setCatParentId(Integer catParentId) {
        this.catParentId = catParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_category.cat_name
     *
     * @return the value of em_category.cat_name
     *
     * @mbg.generated Sun Mar 17 20:04:09 CST 2019
     */
    public String getCatName() {
        return catName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_category.cat_name
     *
     * @param catName the value for em_category.cat_name
     *
     * @mbg.generated Sun Mar 17 20:04:09 CST 2019
     */
    public void setCatName(String catName) {
        this.catName = catName == null ? null : catName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_category.cat_status
     *
     * @return the value of em_category.cat_status
     *
     * @mbg.generated Sun Mar 17 20:04:09 CST 2019
     */
    public Boolean getCatStatus() {
        return catStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_category.cat_status
     *
     * @param catStatus the value for em_category.cat_status
     *
     * @mbg.generated Sun Mar 17 20:04:09 CST 2019
     */
    public void setCatStatus(Boolean catStatus) {
        this.catStatus = catStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_category.sort_order
     *
     * @return the value of em_category.sort_order
     *
     * @mbg.generated Sun Mar 17 20:04:09 CST 2019
     */
    public Integer getSortOrder() {
        return sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_category.sort_order
     *
     * @param sortOrder the value for em_category.sort_order
     *
     * @mbg.generated Sun Mar 17 20:04:09 CST 2019
     */
    public void setSortOrder(Integer sortOrder) {
        this.sortOrder = sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_category.create_time
     *
     * @return the value of em_category.create_time
     *
     * @mbg.generated Sun Mar 17 20:04:09 CST 2019
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_category.create_time
     *
     * @param createTime the value for em_category.create_time
     *
     * @mbg.generated Sun Mar 17 20:04:09 CST 2019
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_category.update_time
     *
     * @return the value of em_category.update_time
     *
     * @mbg.generated Sun Mar 17 20:04:09 CST 2019
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_category.update_time
     *
     * @param updateTime the value for em_category.update_time
     *
     * @mbg.generated Sun Mar 17 20:04:09 CST 2019
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }

}