package com.emall.dataobject;

public class ItemAttrValDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_item_attr_val.attr_key_id
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    private Integer attrKeyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_item_attr_val.item_id
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    private String itemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_item_attr_val.symbol
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    private Integer symbol;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_item_attr_val.attr_value
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    private String attrValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_item_attr_val.attr_img
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    private String attrImg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_item_attr_val.attr_key_id
     *
     * @return the value of em_item_attr_val.attr_key_id
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public Integer getAttrKeyId() {
        return attrKeyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_item_attr_val.attr_key_id
     *
     * @param attrKeyId the value for em_item_attr_val.attr_key_id
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public void setAttrKeyId(Integer attrKeyId) {
        this.attrKeyId = attrKeyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_item_attr_val.item_id
     *
     * @return the value of em_item_attr_val.item_id
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public String getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_item_attr_val.item_id
     *
     * @param itemId the value for em_item_attr_val.item_id
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public void setItemId(String itemId) {
        this.itemId = itemId == null ? null : itemId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_item_attr_val.symbol
     *
     * @return the value of em_item_attr_val.symbol
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public Integer getSymbol() {
        return symbol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_item_attr_val.symbol
     *
     * @param symbol the value for em_item_attr_val.symbol
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public void setSymbol(Integer symbol) {
        this.symbol = symbol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_item_attr_val.attr_value
     *
     * @return the value of em_item_attr_val.attr_value
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public String getAttrValue() {
        return attrValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_item_attr_val.attr_value
     *
     * @param attrValue the value for em_item_attr_val.attr_value
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public void setAttrValue(String attrValue) {
        this.attrValue = attrValue == null ? null : attrValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_item_attr_val.attr_img
     *
     * @return the value of em_item_attr_val.attr_img
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public String getAttrImg() {
        return attrImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_item_attr_val.attr_img
     *
     * @param attrImg the value for em_item_attr_val.attr_img
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public void setAttrImg(String attrImg) {
        this.attrImg = attrImg == null ? null : attrImg.trim();
    }
}