package com.emall.dataobject;

import java.util.Date;

public class ItemDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_item.item_id
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    private String itemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_item.category_id
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    private String categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_item.item_title
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    private String itemTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_item.item_sales
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    private Integer itemSales;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_item.item_main_image
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    private String itemMainImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_item.item_intro_image
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    private String itemIntroImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_item.create_time
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_item.update_time
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_item.item_detail_image
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    private String itemDetailImage;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_item.item_id
     *
     * @return the value of em_item.item_id
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public String getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_item.item_id
     *
     * @param itemId the value for em_item.item_id
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public void setItemId(String itemId) {
        this.itemId = itemId == null ? null : itemId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_item.category_id
     *
     * @return the value of em_item.category_id
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public String getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_item.category_id
     *
     * @param categoryId the value for em_item.category_id
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public void setCategoryId(String categoryId) {
        this.categoryId = categoryId == null ? null : categoryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_item.item_title
     *
     * @return the value of em_item.item_title
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public String getItemTitle() {
        return itemTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_item.item_title
     *
     * @param itemTitle the value for em_item.item_title
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public void setItemTitle(String itemTitle) {
        this.itemTitle = itemTitle == null ? null : itemTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_item.item_sales
     *
     * @return the value of em_item.item_sales
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public Integer getItemSales() {
        return itemSales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_item.item_sales
     *
     * @param itemSales the value for em_item.item_sales
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public void setItemSales(Integer itemSales) {
        this.itemSales = itemSales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_item.item_main_image
     *
     * @return the value of em_item.item_main_image
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public String getItemMainImage() {
        return itemMainImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_item.item_main_image
     *
     * @param itemMainImage the value for em_item.item_main_image
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public void setItemMainImage(String itemMainImage) {
        this.itemMainImage = itemMainImage == null ? null : itemMainImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_item.item_intro_image
     *
     * @return the value of em_item.item_intro_image
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public String getItemIntroImage() {
        return itemIntroImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_item.item_intro_image
     *
     * @param itemIntroImage the value for em_item.item_intro_image
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public void setItemIntroImage(String itemIntroImage) {
        this.itemIntroImage = itemIntroImage == null ? null : itemIntroImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_item.create_time
     *
     * @return the value of em_item.create_time
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_item.create_time
     *
     * @param createTime the value for em_item.create_time
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_item.update_time
     *
     * @return the value of em_item.update_time
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_item.update_time
     *
     * @param updateTime the value for em_item.update_time
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_item.item_detail_image
     *
     * @return the value of em_item.item_detail_image
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public String getItemDetailImage() {
        return itemDetailImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_item.item_detail_image
     *
     * @param itemDetailImage the value for em_item.item_detail_image
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public void setItemDetailImage(String itemDetailImage) {
        this.itemDetailImage = itemDetailImage == null ? null : itemDetailImage.trim();
    }
}