package com.emall.dataobject;

import java.math.BigDecimal;

public class ItemStockDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_item_stock.stock_id
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    private Integer stockId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_item_stock.item_id
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    private String itemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_item_stock.attr_symbol_path
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    private String attrSymbolPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_item_stock.price
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_item_stock.item_status
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    private Byte itemStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_item_stock.stock
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    private Integer stock;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_item_stock.stock_id
     *
     * @return the value of em_item_stock.stock_id
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public Integer getStockId() {
        return stockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_item_stock.stock_id
     *
     * @param stockId the value for em_item_stock.stock_id
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public void setStockId(Integer stockId) {
        this.stockId = stockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_item_stock.item_id
     *
     * @return the value of em_item_stock.item_id
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public String getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_item_stock.item_id
     *
     * @param itemId the value for em_item_stock.item_id
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public void setItemId(String itemId) {
        this.itemId = itemId == null ? null : itemId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_item_stock.attr_symbol_path
     *
     * @return the value of em_item_stock.attr_symbol_path
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public String getAttrSymbolPath() {
        return attrSymbolPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_item_stock.attr_symbol_path
     *
     * @param attrSymbolPath the value for em_item_stock.attr_symbol_path
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public void setAttrSymbolPath(String attrSymbolPath) {
        this.attrSymbolPath = attrSymbolPath == null ? null : attrSymbolPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_item_stock.price
     *
     * @return the value of em_item_stock.price
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_item_stock.price
     *
     * @param price the value for em_item_stock.price
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_item_stock.item_status
     *
     * @return the value of em_item_stock.item_status
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public Byte getItemStatus() {
        return itemStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_item_stock.item_status
     *
     * @param itemStatus the value for em_item_stock.item_status
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public void setItemStatus(Byte itemStatus) {
        this.itemStatus = itemStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_item_stock.stock
     *
     * @return the value of em_item_stock.stock
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public Integer getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_item_stock.stock
     *
     * @param stock the value for em_item_stock.stock
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public void setStock(Integer stock) {
        this.stock = stock;
    }
}