package com.emall.dataobject;

import java.math.BigDecimal;
import java.util.Date;

public class OrderItemDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_order_item.order_item_id
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    private String orderItemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_order_item.user_id
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_order_item.order_id
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_order_item.item_id
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    private String itemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_order_item.item_title
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    private String itemTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_order_item.item_main_image
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    private String itemMainImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_order_item.current_unit_price
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    private BigDecimal currentUnitPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_order_item.amount
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    private Integer amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_order_item.total_price
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    private BigDecimal totalPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_order_item.create_time
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_order_item.update_time
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_order_item.order_item_id
     *
     * @return the value of em_order_item.order_item_id
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public String getOrderItemId() {
        return orderItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_order_item.order_item_id
     *
     * @param orderItemId the value for em_order_item.order_item_id
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public void setOrderItemId(String orderItemId) {
        this.orderItemId = orderItemId == null ? null : orderItemId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_order_item.user_id
     *
     * @return the value of em_order_item.user_id
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_order_item.user_id
     *
     * @param userId the value for em_order_item.user_id
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_order_item.order_id
     *
     * @return the value of em_order_item.order_id
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_order_item.order_id
     *
     * @param orderId the value for em_order_item.order_id
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_order_item.item_id
     *
     * @return the value of em_order_item.item_id
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public String getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_order_item.item_id
     *
     * @param itemId the value for em_order_item.item_id
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public void setItemId(String itemId) {
        this.itemId = itemId == null ? null : itemId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_order_item.item_title
     *
     * @return the value of em_order_item.item_title
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public String getItemTitle() {
        return itemTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_order_item.item_title
     *
     * @param itemTitle the value for em_order_item.item_title
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public void setItemTitle(String itemTitle) {
        this.itemTitle = itemTitle == null ? null : itemTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_order_item.item_main_image
     *
     * @return the value of em_order_item.item_main_image
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public String getItemMainImage() {
        return itemMainImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_order_item.item_main_image
     *
     * @param itemMainImage the value for em_order_item.item_main_image
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public void setItemMainImage(String itemMainImage) {
        this.itemMainImage = itemMainImage == null ? null : itemMainImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_order_item.current_unit_price
     *
     * @return the value of em_order_item.current_unit_price
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public BigDecimal getCurrentUnitPrice() {
        return currentUnitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_order_item.current_unit_price
     *
     * @param currentUnitPrice the value for em_order_item.current_unit_price
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public void setCurrentUnitPrice(BigDecimal currentUnitPrice) {
        this.currentUnitPrice = currentUnitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_order_item.amount
     *
     * @return the value of em_order_item.amount
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_order_item.amount
     *
     * @param amount the value for em_order_item.amount
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_order_item.total_price
     *
     * @return the value of em_order_item.total_price
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public BigDecimal getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_order_item.total_price
     *
     * @param totalPrice the value for em_order_item.total_price
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public void setTotalPrice(BigDecimal totalPrice) {
        this.totalPrice = totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_order_item.create_time
     *
     * @return the value of em_order_item.create_time
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_order_item.create_time
     *
     * @param createTime the value for em_order_item.create_time
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_order_item.update_time
     *
     * @return the value of em_order_item.update_time
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_order_item.update_time
     *
     * @param updateTime the value for em_order_item.update_time
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}