package com.emall.dataobject;

import java.math.BigDecimal;
import java.util.Date;

public class OrderDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_order.order_id
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_order.user_id
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_order.payment
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    private BigDecimal payment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_order.payment_type
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    private Integer paymentType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_order.postage
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    private BigDecimal postage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_order.order_status
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    private Integer orderStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_order.total_price
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    private BigDecimal totalPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_order.payment_time
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    private Date paymentTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_order.send_time
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    private Date sendTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_order.end_time
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_order.close_time
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    private Date closeTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_order.create_time
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_order.update_time
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_order.order_id
     *
     * @return the value of em_order.order_id
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_order.order_id
     *
     * @param orderId the value for em_order.order_id
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_order.user_id
     *
     * @return the value of em_order.user_id
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_order.user_id
     *
     * @param userId the value for em_order.user_id
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_order.payment
     *
     * @return the value of em_order.payment
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public BigDecimal getPayment() {
        return payment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_order.payment
     *
     * @param payment the value for em_order.payment
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public void setPayment(BigDecimal payment) {
        this.payment = payment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_order.payment_type
     *
     * @return the value of em_order.payment_type
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public Integer getPaymentType() {
        return paymentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_order.payment_type
     *
     * @param paymentType the value for em_order.payment_type
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public void setPaymentType(Integer paymentType) {
        this.paymentType = paymentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_order.postage
     *
     * @return the value of em_order.postage
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public BigDecimal getPostage() {
        return postage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_order.postage
     *
     * @param postage the value for em_order.postage
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public void setPostage(BigDecimal postage) {
        this.postage = postage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_order.order_status
     *
     * @return the value of em_order.order_status
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public Integer getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_order.order_status
     *
     * @param orderStatus the value for em_order.order_status
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public void setOrderStatus(Integer orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_order.total_price
     *
     * @return the value of em_order.total_price
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public BigDecimal getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_order.total_price
     *
     * @param totalPrice the value for em_order.total_price
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public void setTotalPrice(BigDecimal totalPrice) {
        this.totalPrice = totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_order.payment_time
     *
     * @return the value of em_order.payment_time
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public Date getPaymentTime() {
        return paymentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_order.payment_time
     *
     * @param paymentTime the value for em_order.payment_time
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public void setPaymentTime(Date paymentTime) {
        this.paymentTime = paymentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_order.send_time
     *
     * @return the value of em_order.send_time
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public Date getSendTime() {
        return sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_order.send_time
     *
     * @param sendTime the value for em_order.send_time
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_order.end_time
     *
     * @return the value of em_order.end_time
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_order.end_time
     *
     * @param endTime the value for em_order.end_time
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_order.close_time
     *
     * @return the value of em_order.close_time
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public Date getCloseTime() {
        return closeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_order.close_time
     *
     * @param closeTime the value for em_order.close_time
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public void setCloseTime(Date closeTime) {
        this.closeTime = closeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_order.create_time
     *
     * @return the value of em_order.create_time
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_order.create_time
     *
     * @param createTime the value for em_order.create_time
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_order.update_time
     *
     * @return the value of em_order.update_time
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_order.update_time
     *
     * @param updateTime the value for em_order.update_time
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}