package com.emall.dataobject;

import java.util.Date;

public class SellerCommentDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_seller_comment.seller_comment_id
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    private String sellerCommentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_seller_comment.order_item_id
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    private String orderItemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_seller_comment.user_id
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_seller_comment.comment
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_seller_comment.comment_type
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    private Byte commentType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_seller_comment.create_time
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_seller_comment.update_time
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_seller_comment.seller_comment_id
     *
     * @return the value of em_seller_comment.seller_comment_id
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public String getSellerCommentId() {
        return sellerCommentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_seller_comment.seller_comment_id
     *
     * @param sellerCommentId the value for em_seller_comment.seller_comment_id
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public void setSellerCommentId(String sellerCommentId) {
        this.sellerCommentId = sellerCommentId == null ? null : sellerCommentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_seller_comment.order_item_id
     *
     * @return the value of em_seller_comment.order_item_id
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public String getOrderItemId() {
        return orderItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_seller_comment.order_item_id
     *
     * @param orderItemId the value for em_seller_comment.order_item_id
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public void setOrderItemId(String orderItemId) {
        this.orderItemId = orderItemId == null ? null : orderItemId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_seller_comment.user_id
     *
     * @return the value of em_seller_comment.user_id
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_seller_comment.user_id
     *
     * @param userId the value for em_seller_comment.user_id
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_seller_comment.comment
     *
     * @return the value of em_seller_comment.comment
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_seller_comment.comment
     *
     * @param comment the value for em_seller_comment.comment
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_seller_comment.comment_type
     *
     * @return the value of em_seller_comment.comment_type
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public Byte getCommentType() {
        return commentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_seller_comment.comment_type
     *
     * @param commentType the value for em_seller_comment.comment_type
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public void setCommentType(Byte commentType) {
        this.commentType = commentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_seller_comment.create_time
     *
     * @return the value of em_seller_comment.create_time
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_seller_comment.create_time
     *
     * @param createTime the value for em_seller_comment.create_time
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_seller_comment.update_time
     *
     * @return the value of em_seller_comment.update_time
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_seller_comment.update_time
     *
     * @param updateTime the value for em_seller_comment.update_time
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}