package com.emall.dataobject;

import java.util.Date;

public class ShufflingFigureDataDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_shufflingFigureData.shuffling_id
     *
     * @mbg.generated Mon Mar 18 20:41:09 CST 2019
     */
    private String shufflingId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_shufflingFigureData.source_url
     *
     * @mbg.generated Mon Mar 18 20:41:09 CST 2019
     */
    private String sourceUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_shufflingFigureData.img_url
     *
     * @mbg.generated Mon Mar 18 20:41:09 CST 2019
     */
    private String imgUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_shufflingFigureData.sorted
     *
     * @mbg.generated Mon Mar 18 20:41:09 CST 2019
     */
    private Boolean sorted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_shufflingFigureData.created_date
     *
     * @mbg.generated Mon Mar 18 20:41:09 CST 2019
     */
    private Date createdDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_shufflingFigureData.updated_date
     *
     * @mbg.generated Mon Mar 18 20:41:09 CST 2019
     */
    private Date updatedDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_shufflingFigureData.item_id
     *
     * @mbg.generated Mon Mar 18 20:41:09 CST 2019
     */
    private String itemId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_shufflingFigureData.shuffling_id
     *
     * @return the value of em_shufflingFigureData.shuffling_id
     *
     * @mbg.generated Mon Mar 18 20:41:09 CST 2019
     */
    public String getShufflingId() {
        return shufflingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_shufflingFigureData.shuffling_id
     *
     * @param shufflingId the value for em_shufflingFigureData.shuffling_id
     *
     * @mbg.generated Mon Mar 18 20:41:09 CST 2019
     */
    public void setShufflingId(String shufflingId) {
        this.shufflingId = shufflingId == null ? null : shufflingId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_shufflingFigureData.source_url
     *
     * @return the value of em_shufflingFigureData.source_url
     *
     * @mbg.generated Mon Mar 18 20:41:09 CST 2019
     */
    public String getSourceUrl() {
        return sourceUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_shufflingFigureData.source_url
     *
     * @param sourceUrl the value for em_shufflingFigureData.source_url
     *
     * @mbg.generated Mon Mar 18 20:41:09 CST 2019
     */
    public void setSourceUrl(String sourceUrl) {
        this.sourceUrl = sourceUrl == null ? null : sourceUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_shufflingFigureData.img_url
     *
     * @return the value of em_shufflingFigureData.img_url
     *
     * @mbg.generated Mon Mar 18 20:41:09 CST 2019
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_shufflingFigureData.img_url
     *
     * @param imgUrl the value for em_shufflingFigureData.img_url
     *
     * @mbg.generated Mon Mar 18 20:41:09 CST 2019
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_shufflingFigureData.sorted
     *
     * @return the value of em_shufflingFigureData.sorted
     *
     * @mbg.generated Mon Mar 18 20:41:09 CST 2019
     */
    public Boolean getSorted() {
        return sorted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_shufflingFigureData.sorted
     *
     * @param sorted the value for em_shufflingFigureData.sorted
     *
     * @mbg.generated Mon Mar 18 20:41:09 CST 2019
     */
    public void setSorted(Boolean sorted) {
        this.sorted = sorted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_shufflingFigureData.created_date
     *
     * @return the value of em_shufflingFigureData.created_date
     *
     * @mbg.generated Mon Mar 18 20:41:09 CST 2019
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_shufflingFigureData.created_date
     *
     * @param createdDate the value for em_shufflingFigureData.created_date
     *
     * @mbg.generated Mon Mar 18 20:41:09 CST 2019
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_shufflingFigureData.updated_date
     *
     * @return the value of em_shufflingFigureData.updated_date
     *
     * @mbg.generated Mon Mar 18 20:41:09 CST 2019
     */
    public Date getUpdatedDate() {
        return updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_shufflingFigureData.updated_date
     *
     * @param updatedDate the value for em_shufflingFigureData.updated_date
     *
     * @mbg.generated Mon Mar 18 20:41:09 CST 2019
     */
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_shufflingFigureData.item_id
     *
     * @return the value of em_shufflingFigureData.item_id
     *
     * @mbg.generated Mon Mar 18 20:41:09 CST 2019
     */
    public String getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_shufflingFigureData.item_id
     *
     * @param itemId the value for em_shufflingFigureData.item_id
     *
     * @mbg.generated Mon Mar 18 20:41:09 CST 2019
     */
    public void setItemId(String itemId) {
        this.itemId = itemId == null ? null : itemId.trim();
    }
}