package com.emall.dataobject;

public class UserPasswordDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_user_password.id
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_user_password.user_id
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_user_password.encrpt_password
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    private String encrptPassword;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_user_password.id
     *
     * @return the value of em_user_password.id
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_user_password.id
     *
     * @param id the value for em_user_password.id
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_user_password.user_id
     *
     * @return the value of em_user_password.user_id
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_user_password.user_id
     *
     * @param userId the value for em_user_password.user_id
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_user_password.encrpt_password
     *
     * @return the value of em_user_password.encrpt_password
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public String getEncrptPassword() {
        return encrptPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_user_password.encrpt_password
     *
     * @param encrptPassword the value for em_user_password.encrpt_password
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    public void setEncrptPassword(String encrptPassword) {
        this.encrptPassword = encrptPassword == null ? null : encrptPassword.trim();
    }
}