package com.emall.dao;

import com.emall.dataobject.AddressDO;

public interface AddressDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_address
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    int deleteByPrimaryKey(String addressId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_address
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    int insert(AddressDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_address
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    int insertSelective(AddressDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_address
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    AddressDO selectByPrimaryKey(String addressId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_address
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    int updateByPrimaryKeySelective(AddressDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_address
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    int updateByPrimaryKey(AddressDO record);
}