package com.emall.dao;

import com.emall.dataobject.ItemAttrValDO;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public interface ItemAttrValDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_item_attr_val
     *
     * @mbg.generated Thu Dec 27 15:26:02 CST 2018
     */
    int insert(ItemAttrValDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_item_attr_val
     *
     * @mbg.generated Thu Dec 27 15:26:02 CST 2018
     */
    int insertSelective(ItemAttrValDO record);
    List<ItemAttrValDO> selectByAttrKeyId(int attrKeyId);
}