package com.emall.dao;

import com.emall.dataobject.ItemDO;
import org.springframework.stereotype.Component;

import java.util.List;
import java.util.Map;

@Component
public interface ItemDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_item
     *
     * @mbg.generated Thu Dec 27 15:26:02 CST 2018
     */
    int deleteByPrimaryKey(String itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_item
     *
     * @mbg.generated Thu Dec 27 15:26:02 CST 2018
     */
    int insert(ItemDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_item
     *
     * @mbg.generated Thu Dec 27 15:26:02 CST 2018
     */
    int insertSelective(ItemDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_item
     *
     * @mbg.generated Thu Dec 27 15:26:02 CST 2018
     */
    ItemDO selectByPrimaryKey(String itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_item
     *
     * @mbg.generated Thu Dec 27 15:26:02 CST 2018
     */
    int updateByPrimaryKeySelective(ItemDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_item
     *
     * @mbg.generated Thu Dec 27 15:26:02 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(ItemDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_item
     *
     * @mbg.generated Thu Dec 27 15:26:02 CST 2018
     */
    int updateByPrimaryKey(ItemDO record);

    List<ItemDO> getItems();
    List<ItemDO> getTopSails(int number);
    int getItemSale(String itemId);
    List<ItemDO> getItemByKeyword(String keyword);

    ItemDO getItemByItemId(String itemId);
    List<ItemDO> getItemByCatId(int catId);
}