package com.emall.dao;

import com.emall.dataobject.ItemDO;

public interface ItemDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_item
     *
     * @mbg.generated Thu Dec 27 15:26:02 CST 2018
     */
    int deleteByPrimaryKey(String itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_item
     *
     * @mbg.generated Thu Dec 27 15:26:02 CST 2018
     */
    int insert(ItemDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_item
     *
     * @mbg.generated Thu Dec 27 15:26:02 CST 2018
     */
    int insertSelective(ItemDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_item
     *
     * @mbg.generated Thu Dec 27 15:26:02 CST 2018
     */
    ItemDO selectByPrimaryKey(String itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_item
     *
     * @mbg.generated Thu Dec 27 15:26:02 CST 2018
     */
    int updateByPrimaryKeySelective(ItemDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_item
     *
     * @mbg.generated Thu Dec 27 15:26:02 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(ItemDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_item
     *
     * @mbg.generated Thu Dec 27 15:26:02 CST 2018
     */
    int updateByPrimaryKey(ItemDO record);
}