package com.emall.dao;

import com.emall.dataobject.ItemAttrValDO;

public interface ItemAttrValDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_item_attr_val
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    int insert(ItemAttrValDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_item_attr_val
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    int insertSelective(ItemAttrValDO record);
}