package com.emall.dao;

import com.emall.dataobject.ItemStockDO;
import org.springframework.stereotype.Component;

import java.util.Map;

@Component
public interface ItemStockDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_item_stock
     *
     * @mbg.generated Thu Dec 27 15:26:02 CST 2018
     */
    int deleteByPrimaryKey(Integer stockId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_item_stock
     *
     * @mbg.generated Thu Dec 27 15:26:02 CST 2018
     */
    int insert(ItemStockDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_item_stock
     *
     * @mbg.generated Thu Dec 27 15:26:02 CST 2018
     */
    int insertSelective(ItemStockDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_item_stock
     *
     * @mbg.generated Thu Dec 27 15:26:02 CST 2018
     */
    ItemStockDO selectByPrimaryKey(Integer stockId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_item_stock
     *
     * @mbg.generated Thu Dec 27 15:26:02 CST 2018
     */
    int updateByPrimaryKeySelective(ItemStockDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_item_stock
     *
     * @mbg.generated Thu Dec 27 15:26:02 CST 2018
     */
    int updateByPrimaryKey(ItemStockDO record);
    ItemStockDO selectByItemIdAndSymbol(Map<String,String> map);
    float getMinPrice(String itemId);
    int getStockByItemId(String itemId);
}