package com.emall.dao;

import com.emall.dataobject.ItemAttrKeyDO;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public interface ItemAttrKeyDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_item_attr_key
     *
     * @mbg.generated Thu Dec 27 15:26:02 CST 2018
     */
    int deleteByPrimaryKey(Integer attrKeyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_item_attr_key
     *
     * @mbg.generated Thu Dec 27 15:26:02 CST 2018
     */
    int insert(ItemAttrKeyDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_item_attr_key
     *
     * @mbg.generated Thu Dec 27 15:26:02 CST 2018
     */
    int insertSelective(ItemAttrKeyDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_item_attr_key
     *
     * @mbg.generated Thu Dec 27 15:26:02 CST 2018
     */
    ItemAttrKeyDO selectByPrimaryKey(Integer attrKeyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_item_attr_key
     *
     * @mbg.generated Thu Dec 27 15:26:02 CST 2018
     */
    int updateByPrimaryKeySelective(ItemAttrKeyDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_item_attr_key
     *
     * @mbg.generated Thu Dec 27 15:26:02 CST 2018
     */
    int updateByPrimaryKey(ItemAttrKeyDO record);

    List<ItemAttrKeyDO> selectByItemId(String itemId);
}