package com.emall.dao;

import com.emall.dataobject.OrderDO;

public interface OrderDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_order
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    int deleteByPrimaryKey(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_order
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    int insert(OrderDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_order
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    int insertSelective(OrderDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_order
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    OrderDO selectByPrimaryKey(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_order
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    int updateByPrimaryKeySelective(OrderDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_order
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    int updateByPrimaryKey(OrderDO record);
}