package com.emall.dao;

import com.emall.dataobject.OrderItemDO;

public interface OrderItemDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_order_item
     *
     * @mbg.generated Thu Dec 27 15:26:02 CST 2018
     */
    int deleteByPrimaryKey(String orderItemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_order_item
     *
     * @mbg.generated Thu Dec 27 15:26:02 CST 2018
     */
    int insert(OrderItemDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_order_item
     *
     * @mbg.generated Thu Dec 27 15:26:02 CST 2018
     */
    int insertSelective(OrderItemDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_order_item
     *
     * @mbg.generated Thu Dec 27 15:26:02 CST 2018
     */
    OrderItemDO selectByPrimaryKey(String orderItemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_order_item
     *
     * @mbg.generated Thu Dec 27 15:26:02 CST 2018
     */
    int updateByPrimaryKeySelective(OrderItemDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_order_item
     *
     * @mbg.generated Thu Dec 27 15:26:02 CST 2018
     */
    int updateByPrimaryKey(OrderItemDO record);
}