package com.emall.dao;

import com.emall.dataobject.SellerCommentDO;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public interface SellerCommentDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_seller_comment
     *
     * @mbg.generated Thu Dec 27 15:26:02 CST 2018
     */
    int deleteByPrimaryKey(String sellerCommentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_seller_comment
     *
     * @mbg.generated Thu Dec 27 15:26:02 CST 2018
     */
    int insert(SellerCommentDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_seller_comment
     *
     * @mbg.generated Thu Dec 27 15:26:02 CST 2018
     */
    int insertSelective(SellerCommentDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_seller_comment
     *
     * @mbg.generated Thu Dec 27 15:26:02 CST 2018
     */
    SellerCommentDO selectByPrimaryKey(String sellerCommentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_seller_comment
     *
     * @mbg.generated Thu Dec 27 15:26:02 CST 2018
     */
    int updateByPrimaryKeySelective(SellerCommentDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_seller_comment
     *
     * @mbg.generated Thu Dec 27 15:26:02 CST 2018
     */
    int updateByPrimaryKey(SellerCommentDO record);

    List<SellerCommentDO> selectByUserId(String userId);
}