package com.emall.dao;

import com.emall.dataobject.UserPasswordDO;

public interface UserPasswordDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_user_password
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_user_password
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    int insert(UserPasswordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_user_password
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    int insertSelective(UserPasswordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_user_password
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    UserPasswordDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_user_password
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    int updateByPrimaryKeySelective(UserPasswordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_user_password
     *
     * @mbg.generated Wed Dec 26 15:53:52 CST 2018
     */
    int updateByPrimaryKey(UserPasswordDO record);
}